// This file is auto-generated by @hey-api/openapi-ts

export const DemandNodeSchema = {
  properties: {
    stop_code: {
      type: 'string',
      title: 'Stop Code',
    },
    lat: {
      type: 'number',
      title: 'Lat',
    },
    lon: {
      type: 'number',
      title: 'Lon',
    },
    pressure_s: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'Pressure S',
    },
    pressure_norm: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'Pressure Norm',
    },
    baseline_s: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'Baseline S',
    },
    event_s: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'Event S',
    },
    events: {
      items: {
        $ref: '#/components/schemas/NodeEvent',
      },
      type: 'array',
      title: 'Events',
    },
  },
  type: 'object',
  required: [
    'stop_code',
    'lat',
    'lon',
    'pressure_s',
    'pressure_norm',
    'baseline_s',
    'event_s',
    'events',
  ],
  title: 'DemandNode',
} as const

export const DemandSurfaceSchema = {
  properties: {
    date: {
      type: 'string',
      title: 'Date',
    },
    resolution_min: {
      type: 'integer',
      title: 'Resolution Min',
    },
    n_ticks: {
      type: 'integer',
      title: 'N Ticks',
    },
    tick_times: {
      items: {
        type: 'string',
      },
      type: 'array',
      title: 'Tick Times',
    },
    nodes: {
      items: {
        $ref: '#/components/schemas/DemandNode',
      },
      type: 'array',
      title: 'Nodes',
    },
  },
  type: 'object',
  required: ['date', 'resolution_min', 'n_ticks', 'tick_times', 'nodes'],
  title: 'DemandSurface',
  description:
    'Shape of demand_<date>.json — the node-keyed 15-min pressure surface.',
} as const

export const EventCurvesSchema = {
  properties: {
    event_id: {
      type: 'string',
      title: 'Event Id',
    },
    label: {
      type: 'string',
      title: 'Label',
    },
    type: {
      type: 'string',
      title: 'Type',
    },
    venue: {
      type: 'string',
      title: 'Venue',
    },
    event_start: {
      type: 'string',
      title: 'Event Start',
    },
    event_end: {
      type: 'string',
      title: 'Event End',
    },
    stops: {
      items: {
        type: 'string',
      },
      type: 'array',
      title: 'Stops',
    },
    legs: {
      items: {
        $ref: '#/components/schemas/Leg',
      },
      type: 'array',
      title: 'Legs',
    },
  },
  type: 'object',
  required: [
    'event_id',
    'label',
    'type',
    'venue',
    'event_start',
    'event_end',
    'stops',
    'legs',
  ],
  title: 'EventCurves',
} as const

export const EventsResponseSchema = {
  properties: {
    date: {
      type: 'string',
      title: 'Date',
    },
    resolution_min: {
      type: 'integer',
      title: 'Resolution Min',
    },
    events: {
      items: {
        $ref: '#/components/schemas/EventCurves',
      },
      type: 'array',
      title: 'Events',
    },
  },
  type: 'object',
  required: ['date', 'resolution_min', 'events'],
  title: 'EventsResponse',
  description: 'Shape of demand_<date>_events.json.',
} as const

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError',
      },
      type: 'array',
      title: 'Detail',
    },
  },
  type: 'object',
  title: 'HTTPValidationError',
} as const

export const LegSchema = {
  properties: {
    from: {
      type: 'string',
      title: 'From',
    },
    to: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'To',
    },
    start: {
      type: 'string',
      title: 'Start',
    },
    end: {
      type: 'string',
      title: 'End',
    },
    peak_s: {
      type: 'number',
      title: 'Peak S',
    },
    pressure_s: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'Pressure S',
    },
    pressure_norm: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'Pressure Norm',
    },
  },
  type: 'object',
  required: [
    'from',
    'to',
    'start',
    'end',
    'peak_s',
    'pressure_s',
    'pressure_norm',
  ],
  title: 'Leg',
} as const

export const NodeEventSchema = {
  properties: {
    event_id: {
      type: 'string',
      title: 'Event Id',
    },
    event_label: {
      type: 'string',
      title: 'Event Label',
    },
    leg: {
      type: 'string',
      title: 'Leg',
    },
    to: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'To',
    },
    multiplier: {
      type: 'number',
      title: 'Multiplier',
    },
    active_ticks: {
      items: {
        type: 'integer',
      },
      type: 'array',
      title: 'Active Ticks',
    },
    contribution_s: {
      items: {
        type: 'number',
      },
      type: 'array',
      title: 'Contribution S',
    },
  },
  type: 'object',
  required: [
    'event_id',
    'event_label',
    'leg',
    'to',
    'multiplier',
    'active_ticks',
    'contribution_s',
  ],
  title: 'NodeEvent',
  description: "One event's contribution to a single stop's event_s series.",
} as const

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'integer',
          },
        ],
      },
      type: 'array',
      title: 'Location',
    },
    msg: {
      type: 'string',
      title: 'Message',
    },
    type: {
      type: 'string',
      title: 'Error Type',
    },
    input: {
      title: 'Input',
    },
    ctx: {
      type: 'object',
      title: 'Context',
    },
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError',
} as const
