// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  GetDemandData,
  GetDemandErrors,
  GetDemandResponses,
  GetEventsData,
  GetEventsErrors,
  GetEventsResponses,
  GetSimData,
  GetSimErrors,
  GetSimResponses,
  HealthHealthGetData,
  HealthHealthGetResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthHealthGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HealthHealthGetResponses,
    unknown,
    ThrowOnError
  >({ url: '/health', ...options })

/**
 * Demand Surface
 *
 * The node-keyed 15-min pressure surface (demand_<date>.json).
 */
export const getDemand = <ThrowOnError extends boolean = false>(
  options: Options<GetDemandData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetDemandResponses,
    GetDemandErrors,
    ThrowOnError
  >({ url: '/demand/{date}', ...options })

/**
 * Event Curves
 *
 * The event-first 1-min curve export (demand_<date>_events.json).
 */
export const getEvents = <ThrowOnError extends boolean = false>(
  options: Options<GetEventsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEventsResponses,
    GetEventsErrors,
    ThrowOnError
  >({ url: '/events/{date}', ...options })

/**
 * Sim Trajectories
 *
 * SUMO bus replay for the date (trajectories_<date>.json).
 */
export const getSim = <ThrowOnError extends boolean = false>(
  options: Options<GetSimData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetSimResponses, GetSimErrors, ThrowOnError>({
    url: '/sim/{date}',
    ...options,
  })
