// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8000' | (string & {})
}

/**
 * BusTrajectory
 */
export type BusTrajectory = {
  /**
   * Id
   */
  id: string
  /**
   * Line
   */
  line: string
  /**
   * Block
   */
  block?: string | null
  /**
   * Flex
   */
  flex?: boolean
  /**
   * Points
   */
  points: Array<Array<number>>
}

/**
 * DemandNode
 */
export type DemandNode = {
  /**
   * Stop Code
   */
  stop_code: string
  /**
   * Lat
   */
  lat: number
  /**
   * Lon
   */
  lon: number
  /**
   * Pressure S
   */
  pressure_s: Array<number>
  /**
   * Pressure Norm
   */
  pressure_norm: Array<number>
  /**
   * Baseline S
   */
  baseline_s: Array<number>
  /**
   * Event S
   */
  event_s: Array<number>
  /**
   * Events
   */
  events: Array<NodeEvent>
}

/**
 * DemandSurface
 *
 * Shape of demand_<date>.json — the node-keyed 15-min pressure surface.
 */
export type DemandSurface = {
  /**
   * Date
   */
  date: string
  /**
   * Resolution Min
   */
  resolution_min: number
  /**
   * N Ticks
   */
  n_ticks: number
  /**
   * Tick Times
   */
  tick_times: Array<string>
  /**
   * Nodes
   */
  nodes: Array<DemandNode>
}

/**
 * EventCurves
 */
export type EventCurves = {
  /**
   * Event Id
   */
  event_id: string
  /**
   * Label
   */
  label: string
  /**
   * Type
   */
  type: string
  /**
   * Venue
   */
  venue: string
  /**
   * Event Start
   */
  event_start: string
  /**
   * Event End
   */
  event_end: string
  /**
   * Stops
   */
  stops: Array<string>
  /**
   * Legs
   */
  legs: Array<Leg>
}

/**
 * EventsResponse
 *
 * Shape of demand_<date>_events.json.
 */
export type EventsResponse = {
  /**
   * Date
   */
  date: string
  /**
   * Resolution Min
   */
  resolution_min: number
  /**
   * Events
   */
  events: Array<EventCurves>
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * Leg
 */
export type Leg = {
  /**
   * From
   */
  from: string
  /**
   * To
   */
  to: string | null
  /**
   * Start
   */
  start: string
  /**
   * End
   */
  end: string
  /**
   * Peak S
   */
  peak_s: number
  /**
   * Pressure S
   */
  pressure_s: Array<number>
  /**
   * Pressure Norm
   */
  pressure_norm: Array<number>
}

/**
 * NodeEvent
 *
 * One event's contribution to a single stop's event_s series.
 */
export type NodeEvent = {
  /**
   * Event Id
   */
  event_id: string
  /**
   * Event Label
   */
  event_label: string
  /**
   * Leg
   */
  leg: string
  /**
   * To
   */
  to: string | null
  /**
   * Multiplier
   */
  multiplier: number
  /**
   * Active Ticks
   */
  active_ticks: Array<number>
  /**
   * Contribution S
   */
  contribution_s: Array<number>
}

/**
 * Trajectories
 *
 * Shape of trajectories_<date>.json — SUMO bus replay for the demo window.
 */
export type Trajectories = {
  /**
   * Date
   */
  date: string
  /**
   * Begin
   */
  begin: number
  /**
   * End
   */
  end: number
  /**
   * Buses
   */
  buses: Array<BusTrajectory>
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
  /**
   * Input
   */
  input?: unknown
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown
  }
}

export type HealthHealthGetData = {
  body?: never
  path?: never
  query?: never
  url: '/health'
}

export type HealthHealthGetResponses = {
  /**
   * Response Health Health Get
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown
  }
}

export type HealthHealthGetResponse =
  HealthHealthGetResponses[keyof HealthHealthGetResponses]

export type GetDemandData = {
  body?: never
  path: {
    /**
     * Date
     */
    date: string
  }
  query?: never
  url: '/demand/{date}'
}

export type GetDemandErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetDemandError = GetDemandErrors[keyof GetDemandErrors]

export type GetDemandResponses = {
  /**
   * Successful Response
   */
  200: DemandSurface
}

export type GetDemandResponse = GetDemandResponses[keyof GetDemandResponses]

export type GetEventsData = {
  body?: never
  path: {
    /**
     * Date
     */
    date: string
  }
  query?: never
  url: '/events/{date}'
}

export type GetEventsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetEventsError = GetEventsErrors[keyof GetEventsErrors]

export type GetEventsResponses = {
  /**
   * Successful Response
   */
  200: EventsResponse
}

export type GetEventsResponse = GetEventsResponses[keyof GetEventsResponses]

export type GetSimData = {
  body?: never
  path: {
    /**
     * Date
     */
    date: string
  }
  query?: never
  url: '/sim/{date}'
}

export type GetSimErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetSimError = GetSimErrors[keyof GetSimErrors]

export type GetSimResponses = {
  /**
   * Successful Response
   */
  200: Trajectories
}

export type GetSimResponse = GetSimResponses[keyof GetSimResponses]
