// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from '@tanstack/react-query'

import { client } from '../client.gen'
import { getDemand, getEvents, healthHealthGet, type Options } from '../sdk.gen'
import type {
  GetDemandData,
  GetDemandError,
  GetDemandResponse,
  GetEventsData,
  GetEventsError,
  GetEventsResponse,
  HealthHealthGetData,
  HealthHealthGetResponse,
} from '../types.gen'

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const healthHealthGetQueryKey = (
  options?: Options<HealthHealthGetData>,
) => createQueryKey('healthHealthGet', options)

/**
 * Health
 */
export const healthHealthGetOptions = (
  options?: Options<HealthHealthGetData>,
) =>
  queryOptions<
    HealthHealthGetResponse,
    DefaultError,
    HealthHealthGetResponse,
    ReturnType<typeof healthHealthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: healthHealthGetQueryKey(options),
  })

export const getDemandQueryKey = (options: Options<GetDemandData>) =>
  createQueryKey('getDemand', options)

/**
 * Demand Surface
 *
 * The node-keyed 15-min pressure surface (demand_<date>.json).
 */
export const getDemandOptions = (options: Options<GetDemandData>) =>
  queryOptions<
    GetDemandResponse,
    GetDemandError,
    GetDemandResponse,
    ReturnType<typeof getDemandQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDemand({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getDemandQueryKey(options),
  })

export const getEventsQueryKey = (options: Options<GetEventsData>) =>
  createQueryKey('getEvents', options)

/**
 * Event Curves
 *
 * The event-first 1-min curve export (demand_<date>_events.json).
 */
export const getEventsOptions = (options: Options<GetEventsData>) =>
  queryOptions<
    GetEventsResponse,
    GetEventsError,
    GetEventsResponse,
    ReturnType<typeof getEventsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEvents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getEventsQueryKey(options),
  })
